# conda env update --prefix ./env --file environment.yml
name: inf6200-h2022
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  # LinumPy - begin
  # Necessary because letting those packages be installed as transient dependencies is a pain. See https://github.com/opencv/opencv-python/issues/387.
  - flake8=3.8.*
  - numpy=1.21.*
  - opencv
  - scipy=1.7.*
  - scikit-image=0.18.*
  - matplotlib=3.4.*
  - pytest=6.2.*
  - pytest-cov=3.0.*
  - tqdm=4.61.*
  - imageio=2.9.*
  - nibabel=3.2.*
  - coverage=6.1.*
  - SimpleITK=2.1.*
  # LinumPy - end
  - pip  # Update pip by running `python -m pip install --upgrade pip`
  - pip:
      - git+ssh://git@bitbucket.org/voxsim/simulation_generator#egg=simulation_generator
