name: inf6200-h2022
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip  # Update pip by running `python -m pip install --upgrade pip`
  - pip:
      - -r requirements.txt
