name: inf6200-h2022
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
      - git+ssh://bitbucket.org/voxsim/simulation_generator#egg=simulation_generator # Install Simulation Generator first
      - git+ssh://gitlab.linum.info.uqam.ca/linum/linumpy#egg=linumpy # Install LinumPy -> for convention purposes
